function modelFile = create_parameter_estimator_model()
%CREATE_PARAMETER_ESTIMATOR_MODEL Create the LS and RLS Simulink test model.

testDirectory = fileparts(mfilename('fullpath'));
projectDirectory = fileparts(testDirectory);
mexModelDirectory = fullfile(projectDirectory, 'mex_mdl');
modelName = 'test_parameter_estimator_simulink';
modelFile = fullfile(testDirectory, [modelName, '.slx']);

addpath(mexModelDirectory);

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

new_system(modelName);

set_param(modelName, ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.1', ...
    'StopTime', '2.0', ...
    'SignalLogging', 'off');

add_block('simulink/Sources/Constant', [modelName, '/RLS One'], ...
    'Value', '1', ...
    'Position', [40, 55, 90, 85]);

add_block('simulink/Sources/Pulse Generator', [modelName, '/RLS Input'], ...
    'PulseType', 'Sample based', ...
    'Amplitude', '1', ...
    'Period', '2', ...
    'PulseWidth', '1', ...
    'PhaseDelay', '0', ...
    'SampleTime', '0.1', ...
    'Position', [40, 115, 90, 145]);

add_block('simulink/Signal Routing/Mux', [modelName, '/RLS Regressor'], ...
    'Inputs', '2', ...
    'Position', [145, 55, 150, 145]);

add_block('simulink/Math Operations/Gain', [modelName, '/True Slope'], ...
    'Gain', '2', ...
    'Position', [145, 170, 200, 200]);

add_block('simulink/Math Operations/Sum', [modelName, '/RLS Measurement'], ...
    'Inputs', '++', ...
    'Position', [245, 100, 270, 145]);

add_block('simulink/Sources/Constant', [modelName, '/Forgetting Factor'], ...
    'Value', '1', ...
    'Position', [220, 205, 270, 235]);

add_block('simulink/User-Defined Functions/S-Function', [modelName, '/RLS'], ...
    'FunctionName', 'sfun_recursive_least_square', ...
    'Parameters', '1000', ...
    'Position', [345, 75, 485, 190]);

add_block('simulink/Sinks/To Workspace', [modelName, '/RLS Theta'], ...
    'VariableName', 'theta_rls', ...
    'SaveFormat', 'Timeseries', ...
    'Position', [555, 75, 655, 105]);

for outputIndex = 2:4
    add_block('simulink/Sinks/Terminator', ...
        [modelName, '/RLS Terminator ', num2str(outputIndex)], ...
        'Position', [555, 90 + 40 * outputIndex, 575, 110 + 40 * outputIndex]);
end

add_line(modelName, 'RLS One/1', 'RLS Regressor/1');
add_line(modelName, 'RLS Input/1', 'RLS Regressor/2');
add_line(modelName, 'RLS Input/1', 'True Slope/1');
add_line(modelName, 'RLS One/1', 'RLS Measurement/1');
add_line(modelName, 'True Slope/1', 'RLS Measurement/2');
add_line(modelName, 'RLS Regressor/1', 'RLS/1');
add_line(modelName, 'RLS Measurement/1', 'RLS/2');
add_line(modelName, 'Forgetting Factor/1', 'RLS/3');

set_param(modelName, 'SimulationCommand', 'update');

add_line(modelName, 'RLS/1', 'RLS Theta/1');
add_line(modelName, 'RLS/2', 'RLS Terminator 2/1');
add_line(modelName, 'RLS/3', 'RLS Terminator 3/1');
add_line(modelName, 'RLS/4', 'RLS Terminator 4/1');

add_block('simulink/Sources/Constant', [modelName, '/LS Regressor'], ...
    'Value', '[1; 1; 1; 1; 0; 1; 2; 3]', ...
    'Position', [40, 335, 150, 375]);

add_block('simulink/Sources/Constant', [modelName, '/LS Measurement'], ...
    'Value', '[1; 3; 5; 7]', ...
    'Position', [40, 405, 150, 445]);

add_block('simulink/Sources/Constant', [modelName, '/LS Weight'], ...
    'Value', 'ones(4,1)', ...
    'Position', [40, 475, 150, 515]);

add_block('simulink/User-Defined Functions/S-Function', [modelName, '/Batch LS'], ...
    'FunctionName', 'sfun_least_square', ...
    'Position', [260, 375, 400, 475]);

add_block('simulink/Sinks/To Workspace', [modelName, '/LS Theta'], ...
    'VariableName', 'theta_ls', ...
    'SaveFormat', 'Timeseries', ...
    'Position', [500, 405, 600, 435]);

add_line(modelName, 'LS Regressor/1', 'Batch LS/1');
add_line(modelName, 'LS Measurement/1', 'Batch LS/2');
add_line(modelName, 'LS Weight/1', 'Batch LS/3');
add_line(modelName, 'Batch LS/1', 'LS Theta/1');

set_param(modelName, 'Location', [120, 80, 1050, 720]);
set_param(modelName, 'InitFcn', [ ...
    'modelFile = get_param(bdroot, ''FileName''); ', ...
    'addpath(fullfile(fileparts(fileparts(modelFile)), ''mex_mdl''));']);
save_system(modelName, modelFile);
close_system(modelName, 0);
end
